import {
  Logo,
  PlatformsIcon,
  FundingWithdrawalsIcon,
  CopyTradingIcon,
  ProfessionalQualificationIcon,
  TradingToolsIcon,
  EducationIcon,
  AboutIcon,
  ContactIcon,
  LegalIcon,
  CareerIcon,
  PressAndNewsIcon,
  HelpCenterIcon,
  CollaborationPartnershipIcon,
  AffiliatePartnershipIcon
} from "../components/shared/icons";

export const MENU_ITEMS = [
  {
    title: "Top Markets",
    subItems: [
      {
        title: "Crypto",
        link: "",
        icon: Logo,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Indices",
        link: "",
        icon: Logo,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Forex",
        link: "",
        icon: Logo,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Commodities",
        link: "",
        icon: Logo,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Shares",
        link: "",
        icon: Logo,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Energies",
        link: "",
        icon: Logo,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "All Markets Overview",
        link: "",
        icon: Logo,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
    ],
  },
  {
    title: "Trading",
    subItems: [
      {
        title: "Platforms",
        link: "",
        isSubtitle: true,
        icon: PlatformsIcon,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "MT4",
        link: "",
        icon: null,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "MT5",
        link: "",
        icon: null,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Funding Withdrawals",
        link: "",
        isSubtitle: true,
        icon: FundingWithdrawalsIcon,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Spreads and Fees",
        link: "",
        icon: null,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Accounts Type",
        link: "",
        icon: null,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Trading With Leverage",
        link: "",
        icon: null,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Copy Trading",
        link: "",
        isSubtitle: true,
        icon: CopyTradingIcon,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Professional Qualification",
        link: "",
        isSubtitle: true,
        icon: ProfessionalQualificationIcon,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Why Trade With Oqtima",
        link: "",
        isSubtitle: true,
        icon: Logo,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Trading Tools",
        link: "",
        isSubtitle: true,
        icon: TradingToolsIcon,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Tradeview",
        link: "",
        icon: null,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Economic Calendar",
        link: "",
        icon: null,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Market Sentiment Tools",
        link: "",
        icon: null,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Education",
        link: "",
        isSubtitle: true,
        icon: EducationIcon,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "How To Videos",
        link: "",
        icon: null,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
    ],
  },
  {
    title: "Company",
    subItems: [
      {
        title: "About",
        link: "",
        icon: AboutIcon,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Contact",
        link: "",
        icon: ContactIcon,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Legal",
        link: "",
        icon: LegalIcon,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Career",
        link: "",
        icon: CareerIcon,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Press and News",
        link: "",
        icon: PressAndNewsIcon,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Help Center (F.A.Q)",
        link: "",
        icon: HelpCenterIcon,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
    ],
  },
  {
    title: "Partners",
    subItems: [
      {
        title: "Collaboration Partnership",
        link: "",
        icon: CollaborationPartnershipIcon,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        title: "Affiliate Partnership",
        link: "",
        icon: AffiliatePartnershipIcon,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
    ],
  },
];
