name: Deploy front to s3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy com
    runs-on: ubuntu-latest
    env:
      REACT_APP_ENTITY: fsa
      REACT_APP_API: example.com
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.S3_KEY_ID }}
            aws-secret-access-key: ${{ secrets.S3_KEY }}
            aws-region: us-east-1
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./public/ s3://oqtima-dev-com --delete
  deploy_eu:
    name: Deploy eu
    runs-on: ubuntu-latest
    env:
      REACT_APP_ENTITY: cysec
      REACT_APP_API: example.com
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.S3_KEY_ID }}
            aws-secret-access-key: ${{ secrets.S3_KEY }}
            aws-region: us-east-1
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./public/ s3://oqtima-dev-eu --delete